services:
  docker-opencode:
    image: registry.cn-hangzhou.aliyuncs.com/jcleng/gitbuild-docker-opencode
    container_name: docker-opencode
    entrypoint: []
    # 每一个终端都是一个端口
    network_mode: host
    volumes:
      # opencode 数据目录/skills
      - opencode_root:/root/
      # 配置mcp
      - ../opencode-config:/root/.config/opencode/
      - /var/run/docker.sock:/var/run/docker.sock
      # 项目目录
      - /home/jcleng/work/mywork/:/home/jcleng/work/mywork/
    working_dir: /home/jcleng/work/mywork/
    # environment:
    #   - http_proxy=socks5://192.168.195.18:20170
    #   - https_proxy=socks5://192.168.195.18:20170
    tty: true
    command: bash
volumes:
  opencode_root:
