services:
  docker-opencode:
    image: registry.cn-hangzhou.aliyuncs.com/jcleng/docker-opencode
    container_name: docker-opencode
    entrypoint: []
    # 每一个终端都是一个端口
    network_mode: host
    volumes:
      # opencode 数据目录/skills
      - opencode_agent:/root/.agents/
      - opencode_share:/root/.local/share/opencode
      - opencode_state:/root/.local/state/opencode
      # 配置mcp
      - ../opencode-config:/root/.config/opencode/
      # 项目目录
      - /home/jcleng/work/mywork/:/home/jcleng/work/mywork/
    working_dir: /home/jcleng/work/mywork/
    environment:
      - PATH=/root/.local/bin:$PATH
      # - ALL_PROXY=socks5://192.168.195.18:20170
    tty: true
    command: bash
volumes:
  opencode_agent:
  opencode_share:
  opencode_state:
